# Generated by Django 4.2.2 on 2023-06-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('CUIT', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
                ('unidad', models.CharField(max_length=5)),
                ('precio_unit', models.FloatField()),
                ('stock', models.FloatField()),
                ('exento', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RecursosHumanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('CUIT', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.CharField(max_length=100)),
                ('CV', models.FileField(upload_to='CVs')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('CUIT', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('comision_porc', models.IntegerField()),
            ],
        ),
    ]
