# Generated by Django 4.2.2 on 2023-06-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_clientes_provincia_vendedores_provincia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='exento',
        ),
    ]
